// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function map(f, p) {
  return p.then(f);
}

function chain(f, p) {
  return p.then(f);
}

function $$catch(f, p) {
  return p.catch((function (x) {
                return Promise.reject(Curry._1(f, x));
              }));
}

function biMap(fail, success, p) {
  return p.then(success, fail);
}

function mapError(f, p) {
  return p.then((function (x) {
                return x;
              }), f);
}

function $$finally(f, g, p) {
  p.then(g, f);
  return /* () */0;
}

function fold(f, g, p) {
  return p.then(g, f);
}

function fromOption(err, opt) {
  if (opt) {
    return Promise.resolve(opt[0]);
  } else {
    return Promise.reject(err);
  }
}

function fromJs(p) {
  return p.then((function (x) {
                return x;
              }));
}

function resolve(prim) {
  return Promise.resolve(prim);
}

function reject(prim) {
  return Promise.reject(prim);
}

function all(prim) {
  return Promise.all(prim);
}

exports.resolve    = resolve;
exports.reject     = reject;
exports.all        = all;
exports.map        = map;
exports.chain      = chain;
exports.$$catch    = $$catch;
exports.biMap      = biMap;
exports.mapError   = mapError;
exports.$$finally  = $$finally;
exports.fold       = fold;
exports.fromOption = fromOption;
exports.fromJs     = fromJs;
/* No side effect */
